[[module.imports]]
  path = "github.com/discaptive/hugo-discaptive"

baseURL = 'https://nenjotsu.github.io'  # Your domain name.
languageCode = 'en-US'
title = 'nenjo.trades market analysis'  # Title of your website
# root = '/blog'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.134.0"


[params]
  github = 'https://github.com/nenjotsu'
  username = 'nenjo.trades'

  # To enable giscus, the GitHub-discussions-based comment section,
  # input the repository for the discussions below. For more details, see
  # https://giscus.app
  # [params.giscus]
    # repo = '[ENTER REPO HERE]'
    # repoId = '[ENTER REPO ID HERE]'
    # category = '[ENTER CATEGORY NAME HERE]'
    # categoryId = '[ENTER CATEGORY ID HERE]'
    # mapping = 'pathname'
    # reactionsEnabled = '1'
    # inputPosition = 'bottom'
    # theme = 'light'
    # lang = 'en'

[pagination]
  pagerSize = 5  # Specify the max number of rows to be returned in list

# Menu items displayed in the header.
[[menus.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menus.main]]
  name = 'Tags'
  url = '/tags'
  weight = 20
[[menus.main]]
  name = 'About'
  url = '/about'
  weight = 30
[[menus.main]]
  identified = 'web'
  name = 'Tech Blogs'
  url = 'https://nenjotsu.github.io/me/'
  weight = 40

[[menus.main]]
  name = 'Contact'
  url = 'https://nenjotsu.github.io/site/contact-me/'
  weight = 50

