[[module.imports]]
  path = "github.com/discaptive/hugo-discaptive"

baseURL = 'https://example.org'  # Your domain name.
languageCode = 'en-US'
title = 'nenjo trades blog'  # Title of your website

[module]
  [module.hugoVersion]
    extended = false
    min = "0.134.0"


[params]
  github = 'https://github.com/nenjotsu'
  username = 'nenjotsu'

  # To enable giscus, the GitHub-discussions-based comment section,
  # input the repository for the discussions below. For more details, see
  # https://giscus.app
  [params.giscus]
    repo = '[ENTER REPO HERE]'
    repoId = '[ENTER REPO ID HERE]'
    category = '[ENTER CATEGORY NAME HERE]'
    categoryId = '[ENTER CATEGORY ID HERE]'
    mapping = 'pathname'
    reactionsEnabled = '1'
    inputPosition = 'bottom'
    theme = 'light'
    lang = 'en'

[pagination]
  pagerSize = 5  # Specify the max number of rows to be returned in list

# Menu items displayed in the header.
[[menus.main]]
  name = 'Contact'
  url = 'mailto:youremail@email.com'
  weight = 1
[[menus.main]]
  name = 'Tags'
  url = '/tags'
  weight = 2
[[menus.main]]
  name = 'About'
  url = '/about'
  weight = 3

