[[module.imports]]
  path = "github.com/discaptive/hugo-discaptive"

baseURL = 'https://nenjotsu.github.io'  # Your domain name.
languageCode = 'en-US'
title = 'nenjo.trades market analysis'  # Title of your website
# root = '/blog'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.134.0"


[params]
  github = 'https://github.com/nenjotsu'
  username = 'nenjo.trades'

  [params.author]
    email = 'nenjotrade@gmail.com'
    name = 'Nenjo Trades'

  # To enable giscus, the GitHub-discussions-based comment section,
  # input the repository for the discussions below. For more details, see
  # https://giscus.app
  [params.giscus]
    repo = 'nenjotsu/blog'
    repoId = 'blog'
    category = 'General'
    categoryId = 'blog'
    mapping = 'pathname'
    reactionsEnabled = '1'
    inputPosition = 'bottom'
    theme = 'light'
    lang = 'en'

[pagination]
  pagerSize = 5  # Specify the max number of rows to be returned in list

# Menu items displayed in the header.
[[menus.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menus.main]]
  name = 'Tags'
  url = '/tags'
  weight = 20
[[menus.main]]
  name = 'About'
  url = '/about'
  weight = 30
[[menus.main]]
  identified = 'web'
  name = 'Tech Blogs'
  url = 'https://nenjotsu.github.io/me/'
  weight = 40

[[menus.main]]
  name = 'Contact'
  url = 'https://nenjotsu.github.io/site/contact-me/'
  weight = 50

[outputs]
  Home = ["html", "rss", "json"]

copyright = '© 2025 nenjotrades'


[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = false
        [markup.goldmark.extensions.extras.superscript]
          enable = false
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoDefinitionTermID = false
      autoHeadingID = true
      autoIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = false
        useEmbedded = 'auto'
      [markup.goldmark.renderHooks.link]
        enableDefault = false
        useEmbedded = 'auto'
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false